image: python:3.7.4
 
before_script:
- python -V # Print out python version for debugging
- pip install .[extras]
 
stages:
- test
 
test_job:
  stage: test
  script:
  - echo "Running tests"
  - export MPLBACKEND="agg"
  - apt-get install -y xvfb
  - export DISPLAY=:99.0
  - export PYVISTA_OFF_SCREEN=true
  - export PYVISTA_USE_PANEL=true
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
  - python -m unittest discover -s "./tests/"