image: python:3.7.4
 
before_script:
- python -V # Print out python version for debugging
- pip install .[extras]
 
stages:
- test
 
test_job:
  stage: test
  script:
  - echo "Running tests"
  - export MPLBACKEND="agg"
  - export PYVISTA_OFF_SCREEN=true
  - python -m unittest discover -s "./tests/"