image: ubuntu:18.04
 
before_script:
- apt-get update -qy 
- apt-get install -y python3.7 python3-pip
- python3 -V # Print out python version for debugging
- pip3 install .[extras]
 
stages:
- test
 
test_job:
  stage: test
  script:
  - echo "Running tests"
  - python3 -m unittest discover -s "./tests/"