image: python:3.7-buster
 
before_script:
- apt-get update
- apt-cache search mesa
- apt-get install -y libxt-dev
- python -V # Print out python version for debugging
- pip install .[extras]
 
stages:
- test
 
test_job:
  stage: test
  script:
  - echo "Running tests"
  - python -m unittest discover -s "./tests/"