channels:
  - conda-forge
dependencies:
  - dftd4
  - geometric
  - libconeangle
  - matplotlib
  - openbabel
  - pip
  - pymeshfix
  - python >= 3.8
  - pyvista
  - pyvistaqt
  - qcengine
  - rdkit
  - spyrmsd
  - vtk
  - xtb-python
  - pip:
      - pyberny
